language: c
sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

env:
  global:
    - LUAROCKS=2.3.0
    # For LuaJIT 2.1, see https://github.com/LuaJIT/LuaJIT/commit/8961a92dd1607108760694af3486b4434602f8be
    - MACOSX_DEPLOYMENT_TARGET=10.12
  matrix:
    - WITH_LUA_ENGINE=Lua LUA=lua5.3
    - WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1

    # LuaRocks 3.4.0
    - LUAROCKS=3.4.0 WITH_LUA_ENGINE=Lua LUA=lua5.4
    - LUAROCKS=3.4.0 WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1

os:
  - linux
  - osx

script:
  - make && make test
  # Setup LuaRocks
  - source .ci/setenv_lua.sh
  # Test rock installation
  - luarocks make
  - test $PWD = `lua -e "print(require'luv'.cwd())"`
  - luarocks remove luv
  # Test the alternate rockspec
  - mkdir build/lib
  - cp build/deps/libuv/libuv_a.a build/lib/libuv.a
  - cp -a deps/libuv/include build
  - luarocks make rockspecs/$(ls rockspecs) LIBUV_DIR=build LUA_COMPAT53_INCDIR=deps/lua-compat-5.3/c-api
  - test $PWD = `lua -e "print(require'luv'.cwd())"`

jobs:
  fast_finish: true
  include:
    - stage: check
      name: bindings coverage
      addons:
        apt: # don't need cmake for this one
      os: linux
      script:
        - ./.ci/bindcov.sh
    - name: clang-asan
      os: linux
      compiler: clang
      env:
        - ASAN_OPTIONS="detect_leaks=1:check_initialization_order=1"
        - UBSAN_OPTIONS="print_stacktrace=1"
        - BUILD_TYPE=Debug
        - WITH_LUA_ENGINE=Lua
      script:
        - CMAKE_OPTIONS="-DCMAKE_C_FLAGS=-fsanitize=address,undefined" make && make test
        # Run with extremely aggressive garbage collection to potentially find more problems
        - ./build/lua -e "collectgarbage('setpause', 0); collectgarbage('setstepmul', 10000000000000)" tests/run.lua
    - name: valgrind
      os: linux
      # Need a more up-to-date Valgrind to dodge https://bugs.kde.org/show_bug.cgi?id=381289
      dist: bionic
      addons:
        apt:
          packages:
            - valgrind
      env:
        - BUILD_TYPE=Debug
        - WITH_LUA_ENGINE=Lua
      script:
        - make
        - valgrind --error-exitcode=1 --leak-check=full --child-silent-after-fork=yes ./build/lua -e "collectgarbage('setpause', 0); collectgarbage('setstepmul', 10000000000000)" tests/run.lua
    - name: process cleanup test
      os: linux
      env:
        - WITH_LUA_ENGINE=Lua
      script:
        - ./tests/test-sigchld-after-lua_close.sh
    - name: minimum supported libuv
      os: linux
      env:
        - WITH_LUA_ENGINE=Lua
        - WITH_SHARED_LIBUV=On
      script:
        - ./.ci/setup_min_libuv.sh
        - CMAKE_OPTIONS="-DCMAKE_PREFIX_PATH=$HOME/.libuv_min" make && make test


    - stage: deploy
      if: tag IS present
      env: WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1
      script: skip
      before_deploy:
        # Setup LuaRocks
        - source .ci/setenv_lua.sh
        - .ci/make_rockspec.sh $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: luv-$TRAVIS_TAG.tar.gz
        overwrite: true
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - luarocks install lua-cjson # required for luarocks upload
        - luarocks upload luv-$TRAVIS_TAG.rockspec --api-key=$LUAROCKS_API_KEY --force

stages:
  - check
  - test
  - deploy

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
